name: deploy

# 代码提交到master分支时触发github action
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        # Fix timestamps
        - name: restore timestamps
          uses: chetan/git-restore-mtime-action@v2

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v3
          with:
              hugo-version: "latest"
              extended: true

        - name: Build Web
          run: hugo -D --minify

        - name: Deploy Web
          uses: peaceiris/actions-gh-pages@v4
          with:
              PERSONAL_TOKEN: ${{ secrets.token }}
              EXTERNAL_REPOSITORY: Rainboylvx/rainboylvx.github.io
              PUBLISH_BRANCH: master
              PUBLISH_DIR: ./public
              commit_message: auto deploy

        - name: Update Blog Server via Webhook
          run: curl -k ${{ secrets.WEBHOOK_URL }}
